# Generated by Django 3.0.5 on 2020-04-04 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_band', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nick_name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=2000)),
                ('created_date', models.DateTimeField()),
                ('ordinal', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('length', models.TimeField(null=True)),
                ('released_date', models.DateTimeField()),
                ('artist', models.ManyToManyField(to='musik_lib.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musik_lib.Collection')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='track',
            field=models.ManyToManyField(to='musik_lib.Track'),
        ),
    ]
