# Generated by Django 3.0.7 on 2020-06-12 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musik_lib', '0002_auto_20200611_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='track',
        ),
    ]
