# Generated by Django 5.1 on 2024-09-04 10:59

import django.db.models.deletion
import musik_lib.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musik_lib', '0005_alter_collection_ordinal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_year', models.PositiveSmallIntegerField(validators=[musik_lib.validators.validate_year])),
                ('spotify_id', models.CharField(max_length=50, null=True)),
                ('album_type', models.CharField(choices=[('CPN', 'Compilation'), ('STD', 'Studio')], default='CPN', max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='trackincollection',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musik_lib.album'),
        ),
    ]
